Repository three-consulting/epoc-frontend, pull requests merged in 2021-11, with the labels that each got.

#19 chore: updated api types
  lib/types/api.ts
Labels: enhancement

#26 Chore/gha
  .github/workflows/main.yml
Labels: enhancement

#33 chore: updated the readme
  README.md
  epoc-compose.yaml
Labels: docs

#39 Feat/new customer modal
  .eslintignore
  components/projects/NewProject/NewCustomer.tsx
  components/projects/NewProject/NewProjectForm.tsx
  package.json
  yarn.lock
Labels: feat

#46 Refactor/auth
  .eslintignore
  .gitignore
  .prettierignore
  amplify.yml
  amplify/.config/project-config.json
  amplify/README.md
  amplify/backend/auth/epocfrontende74b19af/cli-inputs.json
  amplify/backend/backend-config.json
  amplify/backend/tags.json
  amplify/backend/types/amplify-dependent-resources-ref.d.ts
  amplify/cli.json
  amplify/hooks/README.md
  amplify/team-provider-info.json
  components/common/LeftNav.tsx
  components/common/NavBarMobile.tsx
  lib/contexts/AuthContext.tsx
  lib/hooks/useAuth.ts
  lib/mock/createCustomers.ts
  lib/mock/createEmployees.ts
  lib/types/auth.ts
  lib/utils/setAmplify.ts
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/api/customers.ts
  pages/api/employees.ts
  pages/api/hello.ts
  yarn.lock
Labels: feat, refactor, high

#56 test: added lint-staged and the no-console rule for eslint
  .eslintrc.js
  .husky/pre-commit
  package.json
  yarn.lock
Labels: style, medium

#54 feat: added button to archive a project
  pages/projects/[id]/index.tsx
Labels: feat
