Repository three-consulting/epoc-frontend, pull requests merged in 2023-05, with the labels that each got.

#302 Fix timesheet form validation
  components/form/TimesheetForm.tsx
Labels: bug

#303 Add status field to edit employee form
  __tests__/component/form/EditEmployeeForm.test.tsx
  __tests__/fixtures.ts
  components/form/EmployeeForm.tsx
Labels: enhancement

#307 Show status on employee details page
  components/detail/EmployeeDetail.tsx
Labels: enhancement

#310 Filter archived employees from form selections
  components/form/ProjectForm.tsx
  components/form/TimesheetForm.tsx
Labels: enhancement

#312 Remove placeholders from Select components
  components/form/EmployeeForm.tsx
  components/form/FromCsvForm.tsx
  components/form/ProjectForm.tsx
  components/form/TimesheetEntryForm.tsx
  components/form/TimesheetForm.tsx
  components/table/ReportTable/FilterFields.tsx
Labels: chore

#314 Group report-pdf by employee
  components/table/ReportTable/DateInput.tsx
  components/table/ReportTable/TableButtons.tsx
  components/table/ReportTable/utils.ts
Labels: enhancement

#317 Limit the working hours on entry form
  components/common/FormFields.tsx
  components/common/StyledButtons.tsx
  components/form/CustomerForm.tsx
  components/form/EmployeeForm.tsx
  components/form/ProjectForm.tsx
  components/form/TaskForm.tsx
  components/form/TimesheetEntryForm.tsx
  components/form/TimesheetForm.tsx
  components/modal/ImportFromCSVModal.tsx
  components/table/CustomerTable.tsx
  components/table/EmployeeTable.tsx
  components/table/ProjectTable.tsx
  components/table/ReportTable/TableButtons.tsx
  components/table/TaskTable.tsx
  components/table/TimesheetTable.tsx
  pages/customer/[id]/index.tsx
  pages/employee/[id]/index.tsx
  pages/project/[id]/index.tsx
  pages/timesheet/[id]/index.tsx
Labels: chore

#318 Add first page to exported pdf reports
  components/table/ReportTable/utils.ts
Labels: chore
