Repository three-consulting/epoc-frontend, pull requests merged in 2023-06, with the labels that each got.

#320 Add flex to timesheet entry form
  __tests__/component/form/CreateTimesheetEntryForm.test.tsx
  __tests__/component/form/EditTimesheetEntryForm.test.tsx
  __tests__/fixtures.ts
  components/form/TimesheetEntryForm.tsx
  lib/types/api.ts
  lib/types/typeMetadata.ts
Labels: enhancement

#324 Fix types
  lib/types/api.ts
Labels: build

#323 Fix hour grouping on pdf export
  components/table/ReportTable/utils.ts
Labels: bug

#329 Improve type validation comments in pull requests
  .github/workflows/pull-request.yaml
Labels: chore

#336 Show employee flex
  components/editor/TimesheetEntryEditor/index.tsx
  lib/hooks/misc.ts
Labels: enhancement

#340 Calendar tooltip for entries
  components/editor/TimesheetEntryEditor/index.tsx
  styles/Calendar.css
Labels: enhancement

#341 Fix calendar width
  components/editor/TimesheetEntryEditor/index.tsx
Labels: chore

#342 Improve ui
  components/editor/TimesheetEntryEditor/index.tsx
  styles/Calendar.css
Labels: style
